production:

  # AWS access key (required)
  access_key_id: <%= ENV['BUCKETEER_AWS_ACCESS_KEY_ID'] %>

  # AWS secret key (required)
  secret_access_key: <%= ENV['BUCKETEER_AWS_SECRET_ACCESS_KEY'] %>

  # Bucket name (required)
  bucket: <%= ENV['BUCKETEER_BUCKET_NAME'] %>

  # Identifier for the region in which the bucket was created (required)
  region:  <%= ENV['BUCKETEER_AWS_REGION'] %>

  # Folder name inside bucket where uploaded files should be stored (e.g. 'attachments')
  # The default behavior is to store data in the bucket's root directory
  # attachments_folder:

  # Folder where attachment thumbnails are stored
  # thumbnails_folder: thumbnails/

development:
  # Copy configuration from `production` if desired

test:
  # Copy configuration from `production` if desired
