production:

  # AWS access key (required)
  access_key_id: AKIA6NJG5NZBNWPWBY2U

  # AWS secret key (required)
  secret_access_key: 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

  # Bucket name (required)
  bucket: redmine-app-testbucket

  # Identifier for the region in which the bucket was created (required)
  region: us-east-1

  # Folder name inside bucket where uploaded files should be stored (e.g. 'attachments')
  # The default behavior is to store data in the bucket's root directory
  # attachments_folder:

  # Folder where attachment thumbnails are stored
  # thumbnails_folder: thumbnails/

development:
  # Copy configuration from `production` if desired

test:
  # Copy configuration from `production` if desired
