production:
  access_key_id: AKIA6NJG5NZBNWPWBY2U
  secret_access_key: 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
  bucket: redmine-app-testbucket
  folder:
  endpoint:
  secure:
  private:
  expires:
  proxy:
  thumb_folder:

#development:
#  access_key_id:
#  secret_access_key:
#  bucket:
#  folder:
#  endpoint:
#  secure:
#  private:
#  expires:
#  proxy:
#  thumb_folder:

# Uncomment this to run plugin tests with standart redmine script
# test:
#   access_key_id:
#   secret_access_key:
#   bucket:
